-- Additional Columns for SIKAS ERP

ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS is_outsourced BOOLEAN DEFAULT false;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS location VARCHAR(255);

ALTER TABLE revenue ADD COLUMN IF NOT EXISTS weight_tons DECIMAL(10,2) DEFAULT 0;
ALTER TABLE revenue ADD COLUMN IF NOT EXISTS rate_per_ton DECIMAL(10,2) DEFAULT 0;
